version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    depends_on:
      - db
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"

  migrate:
    build: .
    command: flask db upgrade
    environment:
      FLASK_APP: app.py
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
